language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - yarn install
  

script:
  - yarn run installAll
  - yarn run testAll
  - yarn run buildAll