language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - yarn install
  - yarn run installAll

script:
  - yarn run testAll
  - yarn run buildAll